server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          default-label: main
          uri: https://github.com/mathewpardo/config-data
          search-paths: config-data

  application:
    name: config-service


